version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      eslint:
        dependency-type: 'development'
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
        update-types:
          - 'major'
          - 'minor'
      commitlint:
        dependency-type: 'development'
        patterns:
          - '@commitlint/*'
        update-types:
          - 'major'
          - 'minor'
      semantic-release:
        dependency-type: 'development'
        patterns:
          - 'semantic-release'
          - '@semantic-release/*'
          - 'conventional-changelog-conventionalcommits'
        update-types:
          - 'major'
          - 'minor'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'sunday'
