version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    schedule:
      interval: "weekly"
    groups:
      eslint:
        dependency-type: "development"
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
        update-types:
          - "major"
          - "minor"
      commitlint:
        dependency-type: "development"
        patterns:
          - "@commitlint/*"
        update-types:
          - "major"
          - "minor"
      semantic-release:
        dependency-type: "development"
        patterns:
          - "semantic-release"
          - "@semantic-release/*"
          - "conventional-changelog-conventionalcommits"
        update-types:
          - "major"
          - "minor"
  - package-ecosystem: "docker"
    directory: "/"
    commit-message:
      prefix: "build(docker)"
    schedule:
      interval: "monthly"
      day: "sunday"
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "ci(gha)"
    schedule:
      interval: "monthly"
      day: "sunday"
